//go:build windows && 386

// Package libs carries the prebuilt static libraries (OpenCV 4.12.0,
// modules: core,imgproc,features2d,calib3d,objdetect, plus zlib and the cv2 C wrapper) that
// github.com/hkloudou/cv2 links on windows/386.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -static -lstdc++ -lwinpthread -lole32

// Link-time pairing handshake: the root package's init references this
// symbol by name. Mixing library and source generations fails to link.
void cv2_abi_6dc85fc18998(void) {}
*/
import "C"
