//go:build linux && arm64

// Package libs carries the prebuilt static libraries (OpenCV 5.0.0,
// modules: core,imgproc,features,geometry,objdetect, plus zlib and the cv2 C wrapper) that
// github.com/hkloudou/cv2 links on linux/arm64.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -lstdc++ -lm -lpthread -ldl

// Link-time pairing handshake: the root package's init references this
// symbol by name. Mixing library and source generations fails to link.
void cv2_abi_6dc85fc18998(void) {}
*/
import "C"
