//go:build linux && arm64

// Package libs carries the prebuilt static libraries (OpenCV 4.8.1,
// modules: core,imgproc,features2d,calib3d, plus zlib and the cv2 C wrapper) that
// github.com/hkloudou/cv2 links on linux/arm64.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -lstdc++ -lm -lpthread -ldl
*/
import "C"
