//go:build darwin && arm64

// Package libs carries the optional 'qr' feature-set static libraries
// (OpenCV 5.0.0) linked by github.com/hkloudou/cv2/qr on
// darwin/arm64.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2qrwrapper -lopencv_objdetect -lopencv_features -lopencv_geometry -lopencv_flann -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -lc++

// Link-time pairing handshake with the qr subpackage.
void cv2_qr_abi_6dc85fc18998(void) {}
*/
import "C"
