//go:build (linux && (amd64 || 386 || arm64)) || (windows && (amd64 || 386)) || (darwin && arm64)

// Code generated by build/gen-abi.sh. DO NOT EDIT.
//
// Link-time pairing check: the prebuilt libs module for this wrapper
// generation defines cv2_qr_abi_ea6e8875f465. Mixing this source version with libs from
// another generation fails to link, naming the expected hash.
package qr

// extern void cv2_qr_abi_ea6e8875f465(void);
import "C"

func init() {
	C.cv2_qr_abi_ea6e8875f465()
}
