//go:build windows && 386

// Package libs carries the optional 'f2d' feature-set static libraries
// (OpenCV 4.12.0) linked by github.com/hkloudou/cv2/f2d on
// windows/386.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2f2dwrapper -lopencv_calib3d -lopencv_features2d -lopencv_flann -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -static -lstdc++ -lwinpthread
*/
import "C"
