//go:build windows && 386

// Package libs carries the optional 'qr' feature-set static libraries
// (OpenCV 4.12.0) linked by github.com/hkloudou/cv2/qr on
// windows/386.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2qrwrapper -lopencv_objdetect -lopencv_calib3d -lopencv_features2d -lopencv_features -lopencv_flann -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -static -lstdc++ -lwinpthread -lole32

// Link-time pairing handshake with the qr subpackage.
void cv2_qr_abi_6dc85fc18998(void) {}
*/
import "C"
