//go:build windows && amd64

// Package libs carries the optional 'f2d' feature-set static libraries
// (OpenCV 4.12.0) linked by github.com/hkloudou/cv2/f2d on
// windows/amd64.
//
// Generated by build/package-libs.sh. Do not edit.
package libs

/*
#cgo LDFLAGS: -L${SRCDIR} -lcv2f2dwrapper -lopencv_calib3d -lopencv_features2d -lopencv_features -lopencv_flann -lcv2wrapper -lopencv_imgproc -lopencv_core -lzlib -static -lstdc++ -lwinpthread -lole32

// Link-time pairing handshake with the f2d subpackage.
void cv2_f2d_abi_6dc85fc18998(void) {}
*/
import "C"
