//go:build (linux && (amd64 || 386 || arm64)) || (windows && (amd64 || 386)) || (darwin && arm64)

// Code generated by build/gen-abi.sh. DO NOT EDIT.
//
// Link-time pairing check against the f2d feature-set libs module; see
// the root package's counterpart for the rationale.
package f2d

// extern void cv2_f2d_abi_f51b148ea7c5(void);
import "C"

func init() {
	C.cv2_f2d_abi_f51b148ea7c5()
}
